project_id = "sghavrsbomsxrwlpyrln"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.rtmp-webhook]
verify_jwt = false

[functions.create-mux-stream]
verify_jwt = false

[functions.mux-webhook]
verify_jwt = false

[functions.get-stream-status]
verify_jwt = false
